### ISSUE TITLE
Missing/Incomplete cell voltage values

### ISSUE THREAD

**Issue by git-cbri** [thibauddavid/onewheelenhancer-issues#2]
When opening the 1W app, my cell values are replaced by a loading indicator, which changes to a "Start cell tracking" label. When I press the label to load cell values, voltage for only one cell is shown (in slot 14).

I do not believe this is due to a conflicting package as I've tried disabling all other springboard injections and got the same result.

I'm happy to dump a log once the functionality is added.

Thanks!

**Comment by thibauddavid** [comment]
Waiting for logs

**Comment by git-cbri** [comment]
Log attached here!

[console.log](https://github.com/thibauddavid/onewheelenhancer-issues/files/4870627/console.log)
