### ISSUE TITLE
Cell type not displayed (stuck at "Loading" message)

### ISSUE THREAD

**Issue by git-cbri** [thibauddavid/onewheelenhancer-issues#3]
This issue is fairly self-explanatory, 

My cell type does not load in the battery bar, and instead shows "Loading..." forever.

I do not believe this is due to a conflicting package as I've tried disabling all other springboard injections and got the same result.

I'm happy to dump a log once the functionality is added.

Thanks!

**Comment by thibauddavid** [comment]
Waiting for logs

**Comment by git-cbri** [comment]
Log attached here!

[console.log](https://github.com/thibauddavid/onewheelenhancer-issues/files/4870627/console.log)

**Comment by git-cbri** [comment]
Running v1.2.5, I'm getting very low cell voltages that don't seem to match what you told me about my cells previously.
Photo of (possibly incorrect) displayed values and log are attached here.

Thanks!

[console.log](https://github.com/thibauddavid/onewheelenhancer-issues/files/4885319/console.log)

![image1](https://user-images.githubusercontent.com/36866251/86794005-030c5f00-c03a-11ea-90cf-9cc1fc041ac3.png)

**Comment by thibauddavid** [comment]
@git-cbri That's the values your board is sending to the app. I don't understand why you had proper values last time. What battery voltage do you see when switching you gauge battery to XXR mode ?

Edit: 61.1V according to your logs, right ?

**Comment by git-cbri** [comment]
Hmm. Correct, I'm seeing 61.0V in XXR mode.

[console (2).log](https://github.com/thibauddavid/onewheelenhancer-issues/files/4885407/console.2.log)

**Comment by thibauddavid** [comment]
So there is definitely something strange with your cell's level. It's being read correctly but are missing ~1.6V. Maybe some random value is offset from voltage to harden reverse-engineering work. If you restart several time app, you get each time the same values ?

**Comment by git-cbri** [comment]
Dang, that's a bummer. I still get the same values when hard-restarting the app a few times.

**Comment by thibauddavid** [comment]
I'm really curious to know why values where good on your first log now !
Can you keep me in touch if you see more correct values some time ? I'll dig into this !

**Comment by git-cbri** [comment]
Before when you were seeing the correct values in the log, I wasn't able to see correct values in the app either. Just so you know. I will keep in touch for sure if I see the correct values pop up.

**Comment by thibauddavid** [comment]
Yes, that was because I didn't correctly read cell number for 4210 hardware, but voltage was correct. Now, voltage is not what we expect, but that's independent of how I'm reading cells number.
More details [here](https://github.com/OnewheelCommunityEdition/OWCE_App/issues/37#issuecomment-654909982) is you're interested in the different of exchange format

**Comment by thibauddavid** [comment]
@git-cbri Can you recheck using v1.2.6 ? I'm now using builtin cells values used for diagnostic sending so I'm no longer handling myself voltage conversion, you'll get the same value your board is sending to FM 🎁

**Comment by git-cbri** [comment]
You're the man, Thibaud!! I'm now seeing the correct values. 

Closing out this issue.
